FROM ubuntu:22.04

# hadolint ignore=DL3008
RUN apt-get clean && \
    apt-get update -o Acquire::Retries=5 -o Acquire::http::Timeout="20" && \
    apt-get install -y --no-install-recommends \
    gcc \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY flag_tool.c .

RUN gcc flag_tool.c -o flag_tool -lsqlite3

CMD ["tail", "-f", "/dev/null"]