version: '3.8'

services:
  minitwit:
    image: michaelfant/minitwitimage:latest
    env_file:
      - .env
    ports:
      - "8080:5000"
    volumes:
      - minitwit_data:/app/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      update_config:
        delay: 10s
        order: start-first
      restart_policy:
        condition: any

  flagtool:
    image: michaelfant/flagtoolimage:latest
    volumes:
      - minitwit_data:/app/tmp
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    deploy:
      mode: global

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logging/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    deploy:
      mode: global

volumes:
  minitwit_data:
  esdata: