version: '3.8'

networks:
  minitwit_net:
    driver: overlay
    attachable: true

services:
  minitwit:
    image: michaelfant/minitwitimage:latest
    env_file:
      - .env
    ports:
      - "8080:5000"
    networks:
      - minitwit_net
    deploy:
      replicas: 3
      resources:
        reservations:
          memory: 128M
      update_config:
        delay: 10s
        order: start-first
      restart_policy:
        condition: any

  flagtool:
    image: michaelfant/flagtoolimage:latest
    networks:
      - minitwit_net
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 50M

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minitwit_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 256M

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - minitwit_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 128M

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - minitwit_net
    deploy:
      mode: global
      resources:
        reservations:
          memory: 32M

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - minitwit_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 256M

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: promtail_config
        target: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - minitwit_net
    deploy:
      mode: global
      resources:
        reservations:
          memory: 32M

configs:
  promtail_config:
    name: ${PROMTAIL_CONFIG_NAME:-promtail_config}
    external: true

volumes:
  esdata:
