FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pytest requests

COPY . .

CMD ["pytest", "refactored_minitwit_tests.py", "minitwit_sim_api_test.py"]