FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pytest requests

COPY . .

CMD ["pytest", "minitwit_tests_refactor.py", "minitwit_sim_api_test.py", "test_itu_minitwit_ui.py"]