FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    gcc \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY flag_tool.c .

RUN gcc flag_tool.c -o flag_tool -lsqlite3

CMD ["tail", "-f", "/dev/null"]