FROM ubuntu:24.04

# hadolint ignore=DL3008
RUN apt-get clean && \
    apt-get update -o Acquire::Retries=5 -o Acquire::http::Timeout="20" && \
    apt-get install -y --no-install-recommends \
    gcc \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd --system --gid 10001 appuser \
 && useradd  --system --uid 10001 --gid 10001 --create-home appuser

WORKDIR /app

COPY --chown=appuser:appuser flag_tool.c .

RUN gcc flag_tool.c -o flag_tool -lsqlite3 \
 && chown appuser:appuser flag_tool

USER appuser

CMD ["tail", "-f", "/dev/null"]
