[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On

[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L

[FILTER]
    Name   modify
    Match  docker.*
    Add    project  iterroni-minitwit

[OUTPUT]
    Name            es
    Match           docker.*
    Host            elasticsearch
    Port            9200
    Index           minitwit-logs
    Type            _doc
    Logstash_Format On
