{
 "title": "MiniTwit Operations Dashboard",
 "tags": [
  "minitwit",
  "infrastructure"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"minitwit:5000\"}",
     "legendFormat": "App Status"
    }
   ]
  },
  {
   "title": "Function Call Frequencies (Refactoring Candidates)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(minitwit_fct_update_latest_total[1m])",
     "legendFormat": "update_latest()"
    },
    {
     "expr": "rate(minitwit_fct_register_total[1m])",
     "legendFormat": "register()"
    },
    {
     "expr": "rate(minitwit_fct_add_message_total[1m])",
     "legendFormat": "add_message()"
    }
   ]
  },
  {
   "title": "Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[1m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])))",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}