{
 "title": "MiniTwit Software Dashboard",
 "tags": [
  "minitwit",
  "software"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"minitwit:5000\"}",
     "legendFormat": "App Status"
    }
   ]
  },
  {
   "title": "Function Call Frequencies (Refactoring Candidates)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(minitwit_fct_update_latest_total[1m])",
     "legendFormat": "update_latest()"
    },
    {
     "expr": "rate(minitwit_fct_register_total[1m])",
     "legendFormat": "register()"
    },
    {
     "expr": "rate(minitwit_fct_add_message_total[1m])",
     "legendFormat": "add_message()"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_total_users", "legendFormat": "users" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_total_messages", "legendFormat": "messages" }
   ]
  },
  {
   "title": "Total Follows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_total_follows", "legendFormat": "follows" }
   ]
  },
  {
   "title": "Average Followers per User",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_avg_followers", "legendFormat": "avg followers" }
   ]
  },
  {
   "title": "Business Metrics over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "minitwit_total_users", "legendFormat": "users" },
    { "expr": "minitwit_total_messages", "legendFormat": "messages" },
    { "expr": "minitwit_total_follows", "legendFormat": "follows" }
   ]
  }
 ]
}